### PR TITLE
Issues Page: Minor design tweaks

### PR DESCRIPTION
**Pull request by moollaza**
#### Title
- Remove bottom-border
- Remove bottom padding
- Move subtitle beside title

#### Categories & Topics
- Reduce Category heading size, add bottom padding
- Reduce Topic heading size
- Increase "Difficulty" & "Skill" column width
- Reduce bottom-margin for Topic tables

### CODE REVIEW

**Comment by pjhampton** [comment]
@moollaza This looks good to me (screenshot 1). I wonder if it would be a good idea to wrap the **_Help Improve DuckDuckGo search results_** line onto a new line though when users are on a device with a small screen.

**Screenshot 1**

screen shot 2017-03-15 at 7 21 53 pm

**Screenshot 2**

screen shot 2017-03-15 at 7 22 03 pm

**Comment by moollaza** [comment]
> I wonder if it would be a good idea to wrap the Help Improve DuckDuckGo search results line onto a new line though when users are on a device with a small screen.

I was just looking at that -- might need to forgo the inline subtitle because it's a little tricky to handle

**Comment by moollaza** [comment]
@pjhampton I managed to fix it 👍  -- Will share on Asana for review

**Comment by moollaza** [comment]
## Comparison:

ddh issues comparison

**Pull request merged**
