### PR TITLE
Added favicons and metadata

### PR DESCRIPTION
**Pull request by tagawa**
* Created favicon images
* Added tags in head for displaying favicons
* Added metadata for social media snippets

### CODE REVIEW

**Comment by jbarrett** [comment]
Is this what replaced favicon.ico? Yeah, much simpler! 😉

**Comment by tagawa** [comment]
Yeah, that was far too easy! 
I actually tried to learn the various formats but then discovered a [great favicon generator](https://realfavicongenerator.net/) which spurts out both images and code. Still crazy that it's so inconsistent across platforms though.

**Comment by MariagraziaAlastra** [comment]
👍 Thanks!

**Comment by tagawa** [comment]
Grazie @MariagraziaAlastra!

**Pull request merged**
