### PR TITLE
Fix issue button bug on Firefox

### LINKED ISSUE #45: View Open Tasks link on duckduckhack.com doesn't work in Firefox
The "View Open Tasks" button/link located in the "Get Started" section fails to link to the issues page in Firefox. However, it works in Chrome and Edge.

This bug is caused by the hyperlink element being a descendant of the button element. From the bit of looking into it, it looks like this is also against the HTML spec as well, so not really a bug in Firefox.

### PR DESCRIPTION
**Pull request by Gusgus01**
Fixes #45

### CODE REVIEW

**Comment by Gusgus01** [comment]
The anchor tag could also be styled instead of changing the button tag to a div tag, but the div tag kept all the styling the same.

It's a small fix!

**Comment by tagawa** [comment]
Thanks for spotting this and for the fix @Gusgus01. I think we should try to keep the button as a semantically correct `<a>` tag which works better for screenreaders (for users with low/no vision).

**Comment by Gusgus01** [comment]
Oh definitely, the anchor tag is still there and will be read out as a link. I swapped the `<button>` tag for `<div>` tag so that the classes would still be applied and the text remains white. It basically mimics the "Get Started" button/link near the top of the page.

The current site is read as having a button that doesn't respond to the space button and then on the next tab you get the link. My change removes the button read out and leaves only the `<a>`.

**Comment by tagawa** [comment]
@Gusgus01 Ah, my mistake - I skimmed the code too quickly. Thanks for explaining and for the fix 👍

**Comment by Gusgus01** [comment]
No problem. Thanks for maintaining this!

**Pull request merged**
